export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const GET_PRODUCTS_DETAIL_REQUEST = 'GET_PRODUCTS_DETAIL_REQUEST';

export const GET_PRODUCTS_DETAIL_SUCCESS = 'GET_PRODUCTS_DETAIL_SUCCESS';

export const GET_PRODUCTS_DETAIL_ERROR = 'GET_PRODUCTS_DETAIL_ERROR';

export const CREATE_PRODUCTS_REQUEST = 'CREATE_PRODUCTS_REQUEST';

export const CREATE_PRODUCTS_SUCCESS = 'CREATE_PRODUCTS_SUCCESS';

export const CREATE_PRODUCTS_ERROR = 'CREATE_PRODUCTS_ERROR';

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';
